config/routes.rb
Rails.application.routes.draw do
  # Routes pour l'authentification des utilisateurs
  devise_for :users
  devise_scope :user do
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  # Route de recherche pour trouver des albums et des cartes
  get "search", to: "search#index"

  # Définir la racine de l'application
  root to: "pages#home"
  # delete 'collections/:collection_id/albums/:id', to: 'albums#destroy_collection_album', as: 'collection_album'

  # Routes pour les collections
  resources :collections, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :albums, only: [:new, :create]
  end

  delete "/album_pokemons", to: "album_pokemons#destroy_multiple"

  resources :albums, only: [:show, :edit, :update, :destroy]
  # Routes pour les pokemons
  resources :albums, only: [] do
    resources :album_pokemons, only: [:new, :create, :destroy] do
      resources :pokemons, only: [:show]
    end
  end

  resources :pokemons, only: [] do
    member do
      get :render_content
    end
    collection do
      get :search
    end
  end

  # get '/manifest.json', to: redirect('/assets/manifest.json')

end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :user
  has_many :albums, dependent: :destroy
  has_many :pokemons, through: :albums

  validates :name, presence: true
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  def index
    @collections = current_user.collections
  end

  def show
    @seasons = Season.includes(:extensions).all
    @pokemon_ids = @collection.pokemons.ids
  end

  def new
    @collection = current_user.collections.build
  end

  def create
    @collection = current_user.collections.build(collection_params)
    if @collection.save
      redirect_to collection_path(@collection), notice: "Collection créée avec succès."
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @collection.update(collection_params)
      redirect_to collection_path(@collection), notice: "Collection mise à jour avec succès."
    else
      render :edit
    end
  end

  def destroy
    @collection.destroy
    redirect_to collections_path, notice: "Collection supprimée avec succès."
  end

  private

  def set_collection
    @collection = Collection.find(params[:id])
  end

  def collection_params
    params.require(:collection).permit(:name)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/edit.html.erb
<div class="edit-album-container">
  <div class="edit-album-bloc">
    <div class="ms-2">
      <h1 style="font-size: 40px;">Editer la collection</h1>
    </div>

      <%= form_with(model: @collection, url: collection_path(@collection), method: :patch) do |form| %>
        <div class="ms-2 my-4 fs-5">
        <%= form.label :titre %>
        <%= form.text_field :name %>
        </div>
    <div class="my-3 ms-2 d-flex edit-button">
        <%= form.submit "Mettre à jour", class: 'btn', style: "color: #fbfcfa; background: #1e3d59; border-radius: 8px; border: 1px; border-color: $blanc-creme; border-style: solid; cursor: pointer; margin-right: 10px;" %>
      <% end %>
      <%= link_to 'Retour aux collections', collections_path, class: 'btn', style: "color: #fbfcfa; background: #1e3d59; border-radius: 8px; border: 1px; border-color: $blanc-creme; border-style: solid; cursor: pointer; margin-right: 10px;" %>
    </div>
  </div>
</div>

app/views/collections/index.html.erb
<div class="container">
  <h1>Mes Collections</h1>

  <% @collections.each do |collection| %>
    <div class="collection">
      <h2><%= link_to collection.name, collection_path(collection) %></h2>
      <div class="actions">
        <!-- <%= link_to 'Supprimer', collection_path(collection), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>-->
        <%= button_to 'Supprimer', collection_path(collection), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>

      </div>
    </div>
  <% end %>

  <div id="infoText" style="display: none;"> <!-- Élément pour afficher l'explication -->
    <p>Ceci est ta page collection, c'est ici que tu retrouves toutes tes collections de cartes. Clique sur celle que tu veux pour accéder à tes albums.
      Si tu n'en as pas, clique sur le bouton + du menu et crée ta première collection !
    </p>
  </div>
</div>

<%= javascript_include_tag 'info_button' %>
<%= javascript_include_tag 'side_bar_button_show_collection' %>

app/views/collections/new.html.erb
<h1>New Collection</h1>

<%= form_with(model: @collection, url: collections_path, method: :post) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.submit "Create Collection", class: 'btn btn-primary' %>
<% end %>

app/views/collections/show.html.erb
<div class="d-flex flex-column align-items-center">
  <div class="show-collection-name-collection">
    <h1 class="show-collection-h1"><%= @collection.name %></h1>
    <%= link_to edit_collection_path(@collection) do %>
      <%= image_tag("icons-nav/pencil_icon_white1.svg", class: 'show-collection-edit-icon') %>
    <% end %>
  </div>
</div>

<!-- <%= button_to 'Supprimer Collection', collection_path(@collection), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %> -->
<div class="d-flex flex-column align-items-left">

  <div class="d-flex flex-wrap justify-content-center gap-3 mt-3">
    <% @collection.albums.each do |album| %>
      <div class="card-album clicked">
        <%= button_to album_path(album[:id]), method: :get do %>
          <div class="photos-container">
            <%= image_tag(album.getPokemonImg(0), class: 'photos-container-main')%>
            <div class="photos-container-secondary">
              <%= image_tag(album.getPokemonImg(1))%>
              <%= image_tag(album.getPokemonImg(2))%>
            </div>
          </div>
          <div class="card-album-infos row">
            <span class="card-album-name-album"><%= album.name %> </span>
            <span class="card-album-nb-card-album"><%= album.pokemons.size %> <%= album.pokecardcount %></span>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>

<div class="statistic">
  <div class="d-flex flex-column align-items-left show-collection-avancee show-collection-title">

  <div class="container pt-0">
    <div class="row d-flex justify-content-center align-items-center">
      <% @seasons.each do |season| %>
        <div class="col-6 col-sm-6 col-md-4 col-lg-3 my-1">
          <div class="extension-stat clicked" data-controller="toggle" data-action="click->toggle#fire">
            <div class="text-center">
              <h3 class="show-collection-h3"><%= season.season_name %></h3>
              <p class="stats"><%= season.pokemons.where(id: @pokemon_ids).count %>/<%= season.extensions.sum(&:total) %></p>
            </div>
            <div class="card-body">
              <div class="progress mb-1">
                <div class="progress-bar" role="progressbar" style="width: <%= season.pokemons.where(id: @pokemon_ids).count.fdiv(season.extensions.sum(&:total))*100 %>%;" aria-valuenow="<%= season.pokemons.where(id: @pokemon_ids).count.fdiv(season.extensions.sum(&:total))*100 %>" aria-valuemin="0" aria-valuemax="100"></div>
              </div>
              <div class="extension-details d-none" data-toggle-target="extension">
                <% season.extensions.each do |extension| %>
                  <div class="mb-1">
                    <p><b><%= extension.extension_name %></b> : <%= @collection.pokemons.where(extension_id: extension.id).uniq.count %>/<%= extension.total %></p>
                    <div class="progress">
                      <div class="progress-bar bg-info" role="progressbar" style="width: <%= @collection.pokemons.where(extension_id: extension.id).uniq.count.fdiv(extension.total)*100 %>%;" aria-valuenow="<%= @collection.pokemons.where(extension_id: extension.id).uniq.count.fdiv(extension.total)*100 %>" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                  </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
</div>
    </div>

<%= javascript_include_tag 'side_bar_button_show_collection' %>