config/routes.rb
Rails.application.routes.draw do
  # Routes pour l'authentification des utilisateurs
  devise_for :users
  devise_scope :user do
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  # Route de recherche pour trouver des albums et des cartes
  get "search", to: "search#index"

  # Définir la racine de l'application
  root to: "pages#home"
  # delete 'collections/:collection_id/albums/:id', to: 'albums#destroy_collection_album', as: 'collection_album'

  # Routes pour les collections
  resources :collections, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :albums, only: [:new, :create]
  end

  delete "/album_pokemons", to: "album_pokemons#destroy_multiple"

  resources :albums, only: [:show, :edit, :update, :destroy]
  # Routes pour les pokemons
  resources :albums, only: [] do
    resources :album_pokemons, only: [:new, :create, :destroy] do
      resources :pokemons, only: [:show]
    end
  end

  resources :pokemons, only: [] do
    member do
      get :render_content
    end
    collection do
      get :search
    end
  end

  # get '/manifest.json', to: redirect('/assets/manifest.json')

end

app/models/album_pokemon.rb
class AlbumPokemon < ApplicationRecord
  belongs_to :album
  belongs_to :pokemon
end

app/controllers/album_pokemons_controller.rb
class AlbumPokemonsController < ApplicationController
  before_action :set_album
  before_action :set_new_page_flag, only: [:new]

  def new
    load_collection_and_album
    @seasons = Season.includes(:extensions).all
    # find extension if user click on button season
    @extensions = Extension.where("season_id = ?", params[:season_id]) if params[:season_id].present?
    search_pokemon
  end

  def create
    @album_pokemon = @album.album_pokemons.build(pokemon_id: params[:pokemon_id])
    if @album_pokemon.save
      render json: { success: true }
    else
      render json: { success: false, error: @album_pokemon.errors.full_messages.to_sentence }, status: :unprocessable_entity
    end
  end

  def destroy_multiple
    pokemon_ids = params[:pokemon_ids].split(',')
    AlbumPokemon.where(pokemon_id: pokemon_ids).destroy_all
    head :no_content
  end

  private

  def load_collection_and_album
    @album = Album.find(params[:album_id])
    @collection = @album.collection
  end

  def search_pokemon
    if params[:type].present? && params[:extension_id].present?
      @pokemons = Pokemon.where("extension_id = ?", params[:extension_id])
      @pokemons = @pokemons.where("metadata @> ?", { types: [I18n.t("pokemon_types.#{params[:type]}")] }.to_json)
    elsif params[:name].present? && params[:extension_id].present?
      @pokemons = Pokemon.where("pokemons.pokemon_name ILIKE ? OR unaccent(pokemons.pokemon_name) ILIKE ? OR pokemons.pokemon_id ILIKE ?", "%#{params[:name]}%", "%#{params[:name]}%", "%#{params[:name]}%")
      @pokemons = @pokemons.where("extension_id = ?", params[:extension_id])
    elsif params[:extension_id].present?
      # find pokemon where user click on button extension
      @pokemons = Pokemon.where("extension_id = ?", params[:extension_id])
    elsif params[:name].present?
    # find pokemon where user put name
      @pokemons = Pokemon.where("pokemons.pokemon_name ILIKE ? OR unaccent(pokemons.pokemon_name) ILIKE ? OR pokemons.pokemon_id ILIKE ?", "%#{params[:name]}%", "%#{params[:name]}%", "%#{params[:name]}%")
    end
  end

  def set_album
    @album = Album.find_by(id: params[:album_id])
  end

  def set_new_page_flag
    @is_new_page = true
  end
end

app/helpers/album_pokemons_helper.rb
module AlbumPokemonsHelper
end

app/views/album_pokemons/_search-types.html.erb
<div class="type-list-scrollable my-3 px-3">
  <div class="type-list-content">
    <% Pokemon::TYPES.each do |type| %> <!-- get all the types logo to create a link into them -->
      <% if params[:type] == type.to_s %> <!-- regard if the parameter is present to have a toggle search -->
        <%= link_to request.params.except(:type), class:"type-link #{type}" do %> <!-- request.params.except to remove the parameter into the field params -->
          <%= image_tag("energy/#{type}.png", class: "icon-type-search-bar") %>
        <% end %>
      <% else %>
        <%= link_to request.params.merge(type: type), class:"type-link #{type}" do %>  <!-- request.params.merge to create a special params define by the user -->
          <%= image_tag("energy/#{type}.png", class: "icon-type-search-bar") %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

<!-- NB: In the link_to we don't need to put some path cause we want to stay in the current url -->

<script>
  const urlSearchParams = new URLSearchParams(window.location.search);
  const queryParams = Object.fromEntries(urlSearchParams.entries());
  const typelinkList = document.getElementsByClassName("type-link")

  if(queryParams.type) {
    for (let typelink of typelinkList) {
      if(!typelink.classList.contains(queryParams.type)) {
        typelink.classList.add("inactif")
        } else {
        typelink.classList.add("actif")
      }
    };
  }
</script>

app/views/album_pokemons/_search.html.erb
<%= form_with(method: :get) do %>
  <div class="form-group d-flex align-items-center"> <!-- Utilisation de classes flexbox pour aligner les éléments -->
    <div> <!-- Div pour le label -->
      <%= label_tag :pokemon_id, "Nom Pokemon ou son ID :" %>
    </div>
    <div class="ml-3"> <!-- Div pour le champ de texte avec une marge à gauche -->
      <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "Evoli / pop3-13" %>
    </div>
    <div class="ml-3"> <!-- Div pour le bouton de recherche avec une marge à gauche -->
      <%= submit_tag "Recherche", class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

<style>
  #liste-elements ul {
    list-style-type: none; /* Enlève les puces de liste */
    padding-left: 0; /* Enlève le padding par défaut */
  }

  #liste-elements li {
    margin-bottom: 10px; /* Optionnel : Ajuste l'espacement entre les éléments */
  }
</style>

<%# Code to have button of season or extension to find pokemon to add at the album %>

<div class="caroussel">
  <div id="caroussel_season" class="button-container">
    <span class="label">Seasons :</span>
    <% @seasons.each do |season| %>
      <%= link_to season.season_name, request.params.merge(season_id: season.id), class: "button-87", data: { season_id: season.id } %>
    <% end %>
  </div>
</div>

<div class="caroussel">
  <div id="caroussel_season" class="button-container">
    <span class="label">Extensions :</span>
    <% @seasons.each do |season| %>
      <%= link_to season.season_name, request.params.merge(season_id: season.id), class: "button-87" %>
    <% end %>
  </div>
</div>
<div class="button-container">
  <% unless @extensions.nil? %>
    <% @extensions.each do |extension| %>
      <%= link_to extension.extension_name, request.params.merge(extension_id: extension.id, type: nil), class: "button-87" %>
    <% end %>
  <% end %>
</div>

<div id="pokemon_type" class="button-container d-flex flex-wrap justify-content-center">
  <span class="label">Types :</span>
  <% Pokemon::TYPES.each do |type| %>
    <%= link_to request.params.merge(type: type) do %>
    <div>
      <%= image_tag("energy/#{type}.png", class: "type-large-icon") %>
    </div>
    <% end %>
  <% end %>
</div>

<style>
  .extension-bubble {
    display: none;
    position: absolute;
    background-color: white;
    border: 1px solid #ccc;
    padding: 10px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    z-index: 1000;
  }
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
  const seasonButtons = document.querySelectorAll('#caroussel_season .button-87');
  let currentBubble = null;

  seasonButtons.forEach(button => {
    button.addEventListener('click', function(event) {
      event.preventDefault();

      // Masquer la bulle actuelle si une autre est ouverte
      if (currentBubble) {
        currentBubble.style.display = 'none';
      }

      // Trouver la bulle d'extensions correspondante
      const seasonId = this.getAttribute('data-season-id');
      const bubble = document.querySelector(`.extension-bubble[data-season-id="${seasonId}"]`);

      if (bubble) {
        bubble.style.display = 'block';
        currentBubble = bubble;
      }
    });
  });

  // Masquer la bulle si on clique n'importe où ailleurs
  document.addEventListener('click', function(event) {
    if (currentBubble && !event.target.closest('.extension-bubble') && !event.target.closest('#caroussel_season .button-87')) {
      currentBubble.style.display = 'none';
      currentBubble = null;
    }
  });
});

</script>

app/views/album_pokemons/_searchbar.html.erb
<!-- div to controller stimulus search-pokemon who permit to have a first search bar leading to another one -->
<div data-controller="search-pokemon">
  <!-- div for the real search bar with autocomplete -->
  <div class="d-none search-page" data-search-pokemon-target="search">
    <h2>Recherche par nom ou ID du pokemon</h2>
    <%= form_with(method: :get) do %>
      <div class="form-group d-flex"> <!-- Utilisation de classes flexbox pour aligner les éléments -->

        <div class="align-search">
          <div class="float">
            <i class="fa-solid fa-arrow-left mx-3 py-2" data-action="click->search-pokemon#fire"></i>
          </div>
          <div class="float">
            <%= text_field_tag :name, params[:name], class: "form-control float", placeholder: "Evoli / pop3-13", data: { action: "keyup->search-pokemon#search" } %>  <!-- field to have the pokemon name autocomplete -->
          </div>
        </div>
      </div>
    <% end %>

    <div data-search-pokemon-target="results"> <!-- send the result of the search -->
    </div>
  </div>

  <%= form_with(method: :get) do %>
    <div class="form-group d-flex align-items-center"> <!-- Utilisation de classes flexbox pour aligner les éléments -->
      <div class="ml-3 position-relative" data-action="click->search-pokemon#fire"> <!-- Div pour le champ de texte avec une marge à gauche -->
        <%= text_field_tag :name, params[:name], class: "form-control search-input", placeholder: "Chercher un Pokemon" %>
        <i class="fas fa-search search-icon"></i>
      </div>
      <div class="ml-3"> <!-- Div pour le bouton de recherche avec une marge à gauche -->
      </div>
    </div>
  <% end %>
</div>
<%= link_to "Réinitialiser la recherche", request.params.except(:type, :season_id, :name, :extension_id), style: "color: #fbfcfa; cursor: pointer; margin-top: 3px; font-size: 10px; margin-bottom: 12px" %>

  <div class="season-background">
    <div class="season-list-scrollable my-1">
      <div class="season-list-content" style="white-space: nowrap; overflow-x: auto;">

        <% @seasons.each do |season| %>
          <div class="season-and-extensions clicked" id="season-<%= season.id %>" style="display: inline-block; margin-right: 20px; display: flex;">
            <span class="season-name button-scroll"><strong><%= season.season_name %></strong></span>
            <% unless season.extensions.nil? %>
              <div class="button-container clicked" style="display: none;">
                <% season.extensions.each do |extension| %>
                  <%= link_to extension.extension_name, request.params.merge(extension_id: extension.id, type: nil), class: "button-87 season-link button-scroll", style: "color: white; text-decoration: none;" %>
                <% end %>
              </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<%= javascript_include_tag 'extension_bar' %>

app/views/album_pokemons/new.html.erb
<div class="container">
  <h1>Recherche des pokémons</h1>

  <%= render 'searchbar' %>
  <%= render 'search-types' %>
<hr>



  <% if @pokemons&.any? %>
  <% if params[:extension_id].present? %>
    <% selected_extension = @seasons.map(&:extensions).flatten.find { |extension| extension.id == params[:extension_id].to_i } %>
    <% if selected_extension %>
      <h2 style="font-size: smaller; padding-left: 25px;">Extension sélectionnée: <%= selected_extension.extension_name %></h2>
    <% end %>
  <% end %>

    <div class="display-search">
      <div class="cards-container row" data-album-id="<%= @album.id %>" data-album-pokemons-path="<%= album_album_pokemons_path(@album) %>">
        <% @pokemons.each_with_index do |pokemon, index| %>
          <div class="card col-6 col-sm-6 col-md-4 col-lg-3 my-1 position-relative" data-pokemon-id="<%= pokemon.id %>">
            <%= pokemon_image_tag(pokemon, index) %>
             <% if pokemon.image == "/high.webp" %>
            <div class="pokemon-details-new">
              <p><strong>Nom:</strong> <%= pokemon.pokemon_name %></p>
              <p><strong>Saison:</strong> <%= pokemon.pokemon_id %></p>
              <p><strong>Extension:</strong> <%= pokemon.extension_id %></p>
            </div>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <% if params[:name].present? && params[:extension_id].present? %>
      <p style="padding-left: 25px;">Pas de Pokémon trouvé avec ce nom dans cette extension.</p>
    <% else %>
      <p style="padding-left: 25px;">Pas de Pokémon trouvé avec ce nom.</p>
    <% end %>
  <% end %>
</div>

  <%= javascript_include_tag 'search_script' %>
  <%= javascript_include_tag 'side_bar_button_new' %>