config/routes.rb
Rails.application.routes.draw do
  # Routes pour l'authentification des utilisateurs
  devise_for :users
  devise_scope :user do
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  # Route de recherche pour trouver des albums et des cartes
  get "search", to: "search#index"

  # Définir la racine de l'application
  root to: "pages#home"
  # delete 'collections/:collection_id/albums/:id', to: 'albums#destroy_collection_album', as: 'collection_album'

  # Routes pour les collections
  resources :collections, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :albums, only: [:new, :create]
  end

  delete "/album_pokemons", to: "album_pokemons#destroy_multiple"

  resources :albums, only: [:show, :edit, :update, :destroy]
  # Routes pour les pokemons
  resources :albums, only: [] do
    resources :album_pokemons, only: [:new, :create, :destroy] do
      resources :pokemons, only: [:show]
    end
  end

  resources :pokemons, only: [] do
    member do
      get :render_content
    end
    collection do
      get :search
    end
  end

  # get '/manifest.json', to: redirect('/assets/manifest.json')

end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :collection
  # has_many :album_pokemons
  has_many :album_pokemons, dependent: :destroy
  has_many :pokemons, through: :album_pokemons

  validates :name, presence: true

  def getPokemonImg(index)
    if self.pokemons[index].present?
      self.pokemons[index].image
    else
      "card-back.jpg"
    end
  end

  def pokecardcount
    if self.pokemons.size <= 1
      "carte"
    else
      "cartes"
    end
  end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  protect_from_forgery with: :null_session

  before_action :authenticate_user! # Authentifie l'utilisateur avant d'accéder à toute action
  before_action :set_collection, only: [:index, :new, :create] # Définit la collection avant les actions index, new, create
  before_action :set_album, only: [:show, :edit, :update, :destroy] # Définit l'album avant les actions show, edit, update, destroy

  def index
    @albums = @collection.albums # Récupère tous les albums de la collection spécifiée
  end

  def show
    @seasons = Season.includes(:extensions).all
    @extensions = Extension.where("season_id = ?", params[:season_id]) if params[:season_id].present?
    @pokemons = @album.pokemons # Récupère tous les Pokémon associés à l'album spécifique
    search_pokemon
  end

  def new
    @album = @collection.albums.build # Initialise un nouvel album associé à la collection
  end

  def create
    @collection = Collection.find(params[:collection_id]) # Trouve la collection spécifiée dans les paramètres de la requête

    @album = Album.new(album_params)
    @album.collection = @collection
    if @album.save
      redirect_to album_path(@album), notice: "Album créé avec succès." # Redirige vers la page de l'album créé
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @album.update(album_params)
      redirect_to album_path(@album), notice: "Album mise à jour avec succès." # Redirige vers la page de l'album mis à jour
    else
      render :edit # Affiche à nouveau le formulaire d'édition de l'album en cas d'échec
    end
  end

  def destroy
    @album.destroy
    redirect_to collection_path(@album.collection), notice: "Album supprimé avec succès."
  end

  private

  def set_collection
    @collection = Collection.find(params[:collection_id]) # Trouve la collection spécifiée dans les paramètres de la requête
  end

  def set_album
    @album = Album.find(params[:id]) # Trouve l'album spécifié dans les paramètres de la requête
  end

  def album_params
    params.require(:album).permit(:name) # Autorise uniquement le paramètre :name pour la création ou la mise à jour d'un album
  end

  def search_pokemon
    if params[:type].present? && params[:extension_id].present?
      @pokemons = @pokemons.where("extension_id = ?", params[:extension_id])
      @pokemons = @pokemons.where("metadata @> ?", { types: [I18n.t("pokemon_types.#{params[:type]}")] }.to_json)
    elsif params[:name].present? && params[:extension_id].present?
      @pokemons = Pokemon.where("pokemons.pokemon_name ILIKE ? OR unaccent(pokemons.pokemon_name) ILIKE ? OR pokemons.pokemon_id ILIKE ?", "%#{params[:name]}%", "%#{params[:name]}%", "%#{params[:name]}%")
      @pokemons = @pokemons.where("extension_id = ?", params[:extension_id])
    elsif params[:extension_id].present? # find pokemon where user click on button extension
      @pokemons = @pokemons.where("pokemons.extension_id = ?", params[:extension_id])
    elsif params[:name].present? # find pokemon where user put name
      @pokemons = Pokemon.where("pokemons.pokemon_name ILIKE ? OR unaccent(pokemons.pokemon_name) ILIKE ? OR pokemons.pokemon_id ILIKE ?", "%#{params[:name]}%", "%#{params[:name]}%", "%#{params[:name]}%")
    elsif params[:type].present?
      @pokemons = @pokemons.where("metadata @> ?", { types: [I18n.t("pokemon_types.#{params[:type]}")] }.to_json)  # I18n cause we want to traduce the name of types to have the good references with the db
    end
  end
  # I18n : call the function to translate
  # .t('value') : to have the specific method into the function
  # .key('param') : to have the translation of the specific parameter
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/edit.html.erb
<div class="edit-album-container">
  <div class="edit-album-bloc">
    <div class="ms-2">
      <h1 style="font-size: 40px;">Editer l'album</h1>
    </div>

    <%= form_with(model: @album, url: album_path(@album), method: :patch) do |form| %>
      <div class="ms-2 my-4 fs-5">
        <%= form.label :titre %>
        <%= form.text_field :name %>
      </div>

    <div class="my-3 ms-2 d-flex edit-button">
        <%= form.submit "Mettre à jour", class: 'btn', style: "color: #fbfcfa; background: #1e3d59; border-radius: 8px; border: 1px; border-color: $blanc-creme; border-style: solid; cursor: pointer; margin-right: 10px;" %>
      <% end %>
      <%= link_to 'Retour à l\'album', album_path(@album), class: 'btn btn-secondary', style: "color: #fbfcfa; background: #1e3d59; border-radius: 8px; border: 1px; border-color: $blanc-creme; border-style: solid; cursor: pointer; margin-right: 10px;" %>
    </div>
  </div>
</div>

app/views/albums/index.html.erb
<h1>Albums</h1>

<% @albums.each do |album| %>
  <div class="album">
    <h2><%= link_to album.name, collection_album_path(@collection, album) %></h2>
    <%= link_to 'Editer',  edit_collection_album_path(@collection, album) %>
    <%# <%= link_to 'Delete', collection_album_path(@collection, album), method: :delete, data: { confirm: 'Are you sure?' } %> %>
  </div>
<% end %>

<%= link_to 'Ajouter un album', new_collection_album_path(@collection), class: 'btn btn-primary' %>
<%= link_to 'Retour aux collections', collections_path, class: 'btn btn-secondary' %>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= form_with(model: @album, url: collection_albums_path(@collection), method: :post) do |form| %>
  <%= form.label :name, "Album Name" %>
  <%= form.text_field :name %>
  <%= form.hidden_field :collection_id, value: @collection&.id %>
  <%= form.submit "Create Album", class: 'btn btn-primary' %>
<% end %>

<%= link_to 'Back to Albums', collection_path(@collection), class: 'btn btn-secondary' %>

app/views/albums/show.html.erb
<div class="container">
  <div class="show-album-name-album">
    <h1 style="font-size: 40px;"><%= @album.name %></h1>
    <%= link_to edit_album_path(@album) do %>
      <%= image_tag("icons-nav/pencil_icon_white1.svg", class: 'show-pokemon-edit-icon') %>
    <% end %>
  </div>

  <%= render 'album_pokemons/searchbar' %>
  <%= render 'album_pokemons/search-types' %>
  <hr>

  <div class="w-100" data-controller="suppression" id="liste-elements" data-suppression-target="listeElements">
    <ul class="d-flex flex-wrap justify-content-center m-0 p-0 row p-0">
      <% @pokemons.each do |pokemon| %>
        <li class="col-lg-3 col-md-4 col-sm-6 col-6" style="list-style-type: none;">
          <div class="card-container position-relative">
            <div class="img-size">
              <% if pokemon.image != "/high.webp" %>
                <%= link_to image_tag(pokemon.image, class: "pokemon-image clicked", id: "nolink"), album_album_pokemon_pokemon_path(@album.id, pokemon.id) %>
              <% else %>
                <%= link_to album_album_pokemon_pokemon_path(@album.id, pokemon.id) do %>
                  <%= image_tag("Pika-no-image.png", class: "pokemon-image no-image clicked", id: "nolink") %>
                  <div class="pokemon-details">
                    <p><strong>Nom:</strong> <%= pokemon.pokemon_name %></p>
                    <p><strong>Saison:</strong> <%= pokemon.pokemon_id %></p>
                    <p><strong>Extension:</strong> <%= pokemon.extension_id %></p>
                  </div>
                <% end %>
              <% end %>
            </div>
            <div class="text-center mt-2">
              <%= check_box_tag "selected_pokemons[]", pokemon.id, false, { disabled: true, data: { suppression_target: "checkbox" }, style: "display: none;" } %>
            </div>
          </div>
        </li>
      <% end %>
    </ul>
    <% if @pokemons.length <= 0 %>
      <div class="d-flex w-100 justify-content-center text-center">
        <span style="margin-bottom: 18rem; margin-top: 12px;"><%= "Il n'y a pas encore de Pokémon" %></span>
      </div>
    <% end %>
    <button id="deleteSelectedButton" data-action="suppression#supprimerSelection" style="display: none;">
      <i class="fas fa-check" style="color: green; background-color: white; padding: 8px; width: 32px; height: 32px; display: inline-flex; justify-content: center; align-items: center; border-radius: 50%;"></i>
    </button>
    <button id="cancelSelectedButton" onclick="location.reload();" style="display: none;">
      <i class="fas fa-times" style="color: red; background-color: white; padding: 8px; width: 32px; height: 32px; display: inline-flex; justify-content: center; align-items: center; border-radius: 50%;"></i>
    </button>
  </div>
</div>