config/routes.rb
Rails.application.routes.draw do
  # Routes pour l'authentification des utilisateurs
  devise_for :users
  devise_scope :user do
    delete "/users/sign_out", to: "devise/sessions#destroy"
  end

  # Route de recherche pour trouver des albums et des cartes
  get "search", to: "search#index"

  # Définir la racine de l'application
  root to: "pages#home"
  # delete 'collections/:collection_id/albums/:id', to: 'albums#destroy_collection_album', as: 'collection_album'

  # Routes pour les collections
  resources :collections, only: [:index, :new, :create, :show, :edit, :update, :destroy] do
    resources :albums, only: [:new, :create]
  end

  delete "/album_pokemons", to: "album_pokemons#destroy_multiple"

  resources :albums, only: [:show, :edit, :update, :destroy]
  # Routes pour les pokemons
  resources :albums, only: [] do
    resources :album_pokemons, only: [:new, :create, :destroy] do
      resources :pokemons, only: [:show]
    end
  end

  resources :pokemons, only: [] do
    member do
      get :render_content
    end
    collection do
      get :search
    end
  end

  # get '/manifest.json', to: redirect('/assets/manifest.json')

end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  has_many :album_pokemons
  has_many :albums, through: :album_pokemons
  belongs_to :extension
  has_one :season, through: :extension

  validates :pokemon_name, presence: true

  TYPES = [:fire, :water, :grass, :electric, :normal, :fighting, :steel, :psychic, :dragon, :dark, :fairy]

  def self.with_extension_and_season
    joins(extension: :season)
      .select('pokemons.*, extensions.extension_name, seasons.season_name')
  end

  def pokemon_type
    type = self.metadata['types']&.first || 'unknown'
    I18n.t("pokemon_types").key(type)
  end

  def icon_type_src(type)
    type_en = I18n.t("pokemon_types").key(type)
    "energy/#{type_en}.png"
  end
  # I18n : call the function to translate
  # .t('value') : to have the specific method into the function
  # .key('param') : to have the translation of the specific parameter
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  def show

    # @pokemon = Pokemon.includes(name:).find(params[:album_pokemon_id])
    @pokemon = Pokemon.find(params[:album_pokemon_id])
    @album = Album.find(params[:album_id])
    # order pokemons
    pokemons = @album.pokemons
    first_part = pokemons.slice(0, pokemons.index(@pokemon))
    second_part = pokemons.slice(pokemons.index(@pokemon), pokemons.count)
    @reordered_pokemons = second_part.concat(first_part)

    respond_to do |format|
      format.html
      format.json { render json: @pokemon }
    end
  end

  def render_content
    @pokemon = Pokemon.find(params[:id])
    render json: {
      partial: render_to_string(
        partial: "pokemons/pokemon_content",
        locals: { pokemon: @pokemon },
        formats: [:html],
      ),
    }
  end

  def search
    @pokemon_names = Pokemon.where("pokemon_name ILIKE ?", "%#{params[:name]}%").map(&:pokemon_name).uniq

    render json: {
      partial: render_to_string(
        partial: "shared/pokemon_names",
        locals: { pokemon_names: @pokemon_names },
        formats: [:html],
      ),
    }
  end
end

app/views/pokemons/_pokemon_content.html.erb
<div class="info-zone slide-in-bottom" data-carousel-target="content">
  <% if pokemon.category.match?("Pokémon") %>
    <div class="zone fs-6 text">
      <span class="title">Informations</span><br>
      <div class="col"><span>Nom: </span><%= pokemon.pokemon_name %></div>
      <div class="col"><span>Saison - Extension: </span> <%= pokemon.pokemon_id %></div>
      <div class="col">
        <% pokemon.metadata["types"].each do |type| %>
          <span>Type:
            <%= image_tag(pokemon.icon_type_src(type), class: 'icon') %>
          </span>
        <% end %>
      </div>
      <div class="col"><span>Rareté: </span><%= pokemon.rarity %></div>
    </div>
    <div class="zone fs-6 text">
      <span class="title">Attaques et effets</span><br>
        <% pokemon.metadata["attaques"].each do |attaque| %>
          <div class="d-flex flex-column">
            <div class="show-pokemon-attaque-name"><span>Nom: </span><%= attaque["name"] %></div>
            <div class="show-pokemon-attaque-name"><span>Dégat: </span><%= attaque["damage"] %></div>
            <div class="show-pokemon-attaque-name"><span>Effet: </span><%= attaque["effect"] %></div>
          </div>
          <span>Coût:
            <% if attaque["cost"].present? %>
              <% attaque["cost"].each do |cost| %>
                <%= image_tag(pokemon.icon_type_src(cost), class: 'icon text-start') %>
              <% end %>
            <% else %>
              <span>Cost: Non disponible</span>
            <% end %>
          </span>
          <br>
        <% end %>
    </div>
  <% elsif pokemon.category.match?("Dresseur") %>
    <div class="zone fs-6 text">
      <span class="title">Informations</span><br>
      <div class="col"><span>Nom: </span><%= pokemon.pokemon_name %></div>
      <div class="col"><span>Saison - Extension: </span> <%= pokemon.pokemon_id %></div>
      <div class="col"><span>Rareté: </span><%= pokemon.rarity %></div>
    </div>
    <div class="zone fs-6 text">
      <span class="title">Effet</span><br>
      <div class="d-flex flex-column">
        <div class="show-pokemon-attaque-name"><%= pokemon.metadata["effet"] %></div>
      </div>
    </div>
  <% else %>
    <div class="zone fs-6 text">
      <span class="title">Informations</span><br>
      <div class="col"><span>Nom: </span><%= pokemon.pokemon_name %></div>
      <div class="col"><span>Saison - Extension: </span> <%= pokemon.pokemon_id %></div>
      <div class="col"><span>Rareté: </span><%= pokemon.rarity %></div>
    </div>
  <% end %>
</div>

app/views/pokemons/_search.html.erb
<%= form_tag new_user_collection_album_pokemon_path(user, collection, album), method: :get do %>
  <div class="form-group" >
    <%= label_tag :pokemon_id, "Nom Pokemon ou son ID" %>
    <%= text_field_tag :name, params[:name], class: "form-control", placeholder: "Evoli / pop3-13" %>
  </div>
  <%= submit_tag "Search", class: "btn btn-primary" %>
<% end %>

<div data-controller="search">
  <% seasons.each do |season| %>
    <button data-action="click->search#fire"><%= season.season_name %></button>
  <% end %>

</div>

app/views/pokemons/new.html.erb
<h1>Search Pokémon by Name</h1>

<%= render 'search' %>

<% if @pokemons.any? %>
  <h2>Search Results:</h2>
  <%= form_with(model: [@collection, @album, @pokemons], url: user_collection_album_pokemons_path(@collection, @album), method: :post) do |form| %>
    <div class="form-group">
      <%= label_tag :pokemon_id, "Choisis le Pokemon à ajouter" %>
      <%= select_tag :pokemon_id, options_from_collection_for_select(@pokemons, :id, :pokemon_id), { prompt: "Pokémon", class: "form-control" } %>
    </div>
    <%= submit_tag "Add Pokémon", class: "btn btn-primary" %>
  <% end %>
  <ul>
    <% @pokemons.each do |pokemon| %>
      <li><p><%= pokemon.pokemon_name %> / <%= pokemon.pokemon_id %></p><img src="<%= pokemon.image %>" alt="<%= pokemon.pokemon_name %>"></li>
    <% end %>
  </ul>

<% else %>
  <p>No Pokemon found with the given name.</p>
<% end %>

<%= link_to "Back", user_collection_album_path(@user, @collection, @album), class: "btn btn-secondary" %>

app/views/pokemons/show.html.erb
<div class="container" data-controller="carousel" data-carousel-pokemon-count-value="<%= @album.pokemons.count %>">
  <div class="all-infos">
    <div class="contain x mandatory-scroll-snapping" data-action="scrollend->carousel#end" >
      <% @reordered_pokemons.each_with_index do |pokemon, index| %>
        <%= pokemon_image_tag(pokemon, index) %>
      <% end %>
    </div>
    <%= render "pokemon_content", pokemon: @pokemon %>
  </div>
</div>

<%= javascript_include_tag 'side_bar_pokemon_show' %>